# Generated by Django 3.2.18 on 2023-03-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(default='Сингл', on_delete=django.db.models.deletion.PROTECT, to='songs.album', verbose_name='Альбом'),
        ),
    ]
