# Generated by Django 3.2.18 on 2023-03-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_songs_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['id'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AddField(
            model_name='songs',
            name='is_single',
            field=models.BooleanField(default=True, verbose_name='Сингл'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='songs.album', verbose_name='Альбом'),
        ),
    ]
