# Generated by Django 3.2.18 on 2023-04-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_songs_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Навание жанра'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='content',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_songs', to='songs.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название песни'),
        ),
    ]
