# Generated by Django 3.2.18 on 2023-04-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20230402_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='content',
            field=models.TextField(max_length=50000, verbose_name='Информация'),
        ),
    ]
