# Generated by Django 3.2.18 on 2023-04-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_songs_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['title'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_album', to='songs.author', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='author',
            name='content',
            field=models.TextField(blank=True, max_length=50000, verbose_name='Про исполнителя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Навание жанра'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_songs', to='songs.album', verbose_name='Альбом'),
        ),
        migrations.RemoveField(
            model_name='songs',
            name='author',
        ),
        migrations.AddField(
            model_name='songs',
            name='author',
            field=models.ManyToManyField(related_name='get_songs', to='songs.Author', verbose_name='Исполнители'),
        ),
        migrations.RemoveField(
            model_name='songs',
            name='genre',
        ),
        migrations.AddField(
            model_name='songs',
            name='genre',
            field=models.ManyToManyField(related_name='get_songs', to='songs.Genre', verbose_name='Жанры'),
        ),
    ]
